### ISSUE TITLE
EQISにおけるADC値からGALへの変換方法についての質問です

### ISSUE THREAD

**Issue by AstroTaka** [ingen084/seismometer#2]
PiDASとEQISのADC値からGALへの変換部分を見比べていて分からない部分がありましたので質問をさせて頂きます。

以下の部分がPiDASにおけるADC値からGALへの変換部分だと思うのですが
https://github.com/ingen084/seismometer/blob/e9e8603343bcafb4864c5233ac979aab707acf7b/board-lib/PiDAS/Board.h#L49
同様にEQISの部分を見るとライブラリの返値のみを使用していて
https://github.com/ingen084/seismometer/blob/e9e8603343bcafb4864c5233ac979aab707acf7b/board-lib/EQIS/Board.h#L42
これを辿っていくと以下の様に0.061が返りますが、これはLSM6DSOのデータシートの"Linear acceleration sensitivity"にある0.061の事であると思われ、単位はmg/LSBですのでGALに変換するときは重力加速度をかける必要があると思うのですが、いかがでしょうか？
https://github.com/ingen084/seismometer/blob/e9e8603343bcafb4864c5233ac979aab707acf7b/board-lib/EQIS/LSM6DSO.h#L18-L23
https://github.com/stm32duino/LSM6DSO/blob/972aac7ef59fc0502998173da16eee19fb6eadf2/src/LSM6DSOSensor.cpp#L250-L266
https://github.com/stm32duino/LSM6DSO/blob/972aac7ef59fc0502998173da16eee19fb6eadf2/src/LSM6DSOSensor.h#L60

`#define LSM6DSO_ACC_SENSITIVITY_FS_2G   0.061f`

ちなみに以下のブログのソースを見ると重力加速度をかけているようです。
https://qiita.com/compo031/items/e62d0a0e1425c5e1efe8
```
  // LSM6DSO
  byte bs3[6];
  spiRead(spiSettings0, lsm6dsoPin, 0x28, 1, &bs3, sizeof(bs3));
  int16_t xRaw3 = bs3[0] | (bs3[1] << 8);
  int16_t yRaw3 = bs3[2] | (bs3[3] << 8);
  int16_t zRaw3 = bs3[4] | (bs3[5] << 8);
  float x3 = xRaw3 * 0.061 * 0.001 * 9.80665;
  float y3 = yRaw3 * 0.061 * 0.001 * 9.80665;
  float z3 = zRaw3 * 0.061 * 0.001 * 9.80665;
```

また以下の部分につきまして重力加速度は必要ないでしょうか？
https://github.com/ingen084/seismometer/blob/e9e8603343bcafb4864c5233ac979aab707acf7b/board-lib/EQIS/Board.h#L18-L19
PiDASの部分と比較すると必用そうに見えますがいかがでしょうか？
https://github.com/ingen084/seismometer/blob/e9e8603343bcafb4864c5233ac979aab707acf7b/board-lib/PiDAS/Board.h#L18-L19
また以下の部分につきまして上記のブログをふまえると`0.061`から`0.061*0.001*9.80665*100`の値に変更が必要と思うのですがいかがでしょうか？
https://github.com/ingen084/seismometer/blob/e9e8603343bcafb4864c5233ac979aab707acf7b/README.md?plain=1#L87-L93

**Comment by ingen084** [comment]
確かにそうですね…ちょっと仕事が忙しいので週末になってしまうかもしれませんが、確認してみます

**Comment by AstroTaka** [comment]
ありがとうございます。よろしくお願いします。

**Comment by ingen084** [comment]
確認してみましたが、ご指摘の通り誤りがありました。
修正をリリースさせて頂きます。
ありがとうございました。

**Comment by AstroTaka** [comment]
ありがとうございます。

ちょっとすっきりしない所がありまして
getSensitivityで`* 980.665f * 0.001f`を追加していて
`SEISMOMETER_ADC_STEP`でも更に`* 980.665f * 0.001f`を追加していますが
ここは変えなくても良いのかなと思いましたがいかがでしょうか？

**Comment by ingen084** [comment]
`SEISMOMETER_ADC_STEP` の方を先に修正して `getSensitivity` を後から修正したときの誤りなので修正予定です！
(手元の方では修正済みですが、ちょっとPCが不安定で反映できてなかったようです)

**Comment by AstroTaka** [comment]
ありがとうございます

**Comment by AstroTaka** [comment]
この件とは関係無いのですが、READMEに書いてありました`Stationary checking...`の件につきまして
ステーショナリーと聞いて文房具を思い浮かべてしまったという事もありましたので
`Startup checking...`とすることもできるのかなと思いました

**Comment by ingen084** [comment]
`Stability checking...` とかでも良いかもしれませんね…考え中です…

**Comment by AstroTaka** [comment]
よく使われる単語ですし意味も具体的なので良いと思います
